module.exports = {
  LOGIN_EMAIL_ERROR: 'Невірний емейл',
  LOGIN_EMAIL_EMPTY: 'Необхідно вказати емейл',
  LOGIN_USER_NOT_FOUND: 'Користувач з таким емейлом не знайдено',
  LOGIN_PASSWORD_EMPTY: 'Необхідно вказати пароль',
  LOGIN_PASSWORD_IS_INCORRECT: 'Неправильний пароль. Спробуйте знову',
  POSITION_LENGTH_ERROR: 'Назва має бути між 2 та 30 символами',
  POSITION_NAME_ERROR: 'Необхідно вказати назву',
  POSITION_PRICE_ERROR: 'Необхідно вказати ціну',
  POSITION_DELETE_SUCCESSFUL: 'Позицію було успішно видалено',
  REGISTER_NAME_LENGTH_ERROR: "Ім'я має бути між 2 та 30 символами",
  REGISTER_NAME_ERROR: "Необхідно вказати ім'я",
  REGISTER_EMAIL_EMPTY: 'Необхідно вказати емейл',
  REGISTER_EMAIL_ERROR: 'Невірний емейл',
  REGISTER_PASSWORD_EMPTY: 'Необхідно вказати пароль',
  REGISTER_PASSWORD_LENGTH_ERROR: 'Пароль має бути щонайменше з 6 символів',
  REGISTER_PASSWORD_CONFIRM_ERROR: 'Необхідно вказати Підтвердження Паролю',
  REGISTER_PASSWORD_MISMATCH_ERROR: 'Паролі не співпадають',
  ORDER_CREATE_SUCCESSFUL: 'Замовлення успішно створено',
  FILE_HOSTING_ERROR: 'Файл не було опубліковано',
  FILE_HOSTING_SUCCESSFUL: 'Файл успішно збережено',
  FILE_DELETE_SUCCESSFUL: 'Файл успішно видалено',
  CATEGORY_DELETE_SUCCESSFUL: 'Категорію видалено',
};
