export const TYPES = {
  ANALYTICS_LOADING: 'ANALYTICS_LOADING',
  GET_OVERVIEW: 'GET_OVERVIEW',
  GET_ANALYTICS: 'GET_ANALYTICS',
  ERROR_OVERVIEW: 'ERROR_OVERVIEW',
  ERROR_ANALYTICS: 'ERROR_ANALYTICS',
};
