export const TYPES = {
  CATEGORIES_LOADING: 'CATEGORIES_LOADNG',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_CATEGORY: 'GET_CATEGORY',
  ADD_CATEGORY: 'ADD_CATEGORY',
  ADD_CATEGORY_IMAGE: 'ADD_CATEGORY_IMAGE',
  REMOVE_CATEGORY_IMAGE: 'REMOVE_CATEGORY_IMAGE',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  ERROR_CATEGORIES: 'ERROR_CATEGORIES',
};
