export const TYPES = {
  ORDERS_LOADING: 'ORDERS_LOADING',
  FORM_THE_ORDER: 'FORM_THE_ORDER',
  REMOVE_POSITION_FROM_ORDER: 'REMOVE_POSITION_FROM_ORDER',
  GET_ORDERS: 'GET_ORDERS',
  GET_ORDER: 'GET_ORDER',
  ADD_ORDER: 'ADD_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',
  ERROR_ORDERS: 'ERROR_ORDERS',
};
