export const TYPES = {
  POSITIONS_LOADING: 'POSITIONS_LOADNG',
  GET_POSITIONS: 'GET_POSITIONS',
  GET_POSITION: 'GET_POSITION',
  ADD_POSITION: 'ADD_POSITION',
  UPDATE_POSITION: 'UPDATE_POSITION',
  DELETE_POSITION: 'DELETE_POSITION',
  ERROR_POSITIONS: 'ERROR_POSITIONS',
};
